<?php

$tool = static function (
    string $slug,
    string $name,
    string $category,
    string $summary,
    array $options = []
): array {
    $description = $options['description'] ?? $summary;
    $keywords = $options['keywords'] ?? [$name, 'WY Tools', '무료 온라인 도구'];
    $related = $options['related'] ?? [];

    return array_merge($options, [
        'slug' => $slug,
        'url' => '/tools/' . $slug,
        'name' => $name,
        'h1' => $name,
        'category' => $category,
        'summary' => $summary,
        'description' => $description,
        'meta_title' => $name . ' | WY Tools',
        'meta_description' => $description,
        'keywords' => implode(', ', $keywords),
        'status' => $options['status'] ?? 'active',
        'widget' => $options['widget'] ?? 'generic',
        'is_popular' => (bool)($options['is_popular'] ?? false),
        'is_recent' => (bool)($options['is_recent'] ?? false),
        'is_frequent' => (bool)($options['is_frequent'] ?? false),
        'how_to_use' => $options['how_to_use'] ?? [
            '입력 영역에 변환하거나 확인할 값을 입력합니다.',
            '도구가 제공하는 옵션을 선택한 뒤 결과를 확인합니다.',
            '필요한 결과는 복사하거나 공유해서 사용할 수 있습니다.',
        ],
        'examples' => $options['examples'] ?? [
            [
                'title' => $name . ' 사용 예시',
                'input' => '업무나 학습 중 변환이 필요한 데이터를 입력합니다.',
                'output' => '브라우저에서 즉시 처리된 결과를 확인합니다.',
            ],
        ],
        'faqs' => $options['faqs'] ?? [
            [
                'q' => $name . '는 무료인가요?',
                'a' => '네. WY Tools의 기본 온라인 도구는 무료로 사용할 수 있습니다.',
            ],
            [
                'q' => '입력한 데이터는 서버에 저장되나요?',
                'a' => '가능한 기능은 브라우저에서 처리하며, 입력값을 서버에 저장하지 않는 구조를 우선합니다.',
            ],
        ],
        'related' => $related,
        'premium_ready' => (bool)($options['premium_ready'] ?? false),
        'api_ready' => (bool)($options['api_ready'] ?? false),
    ], $options);
};

return [
    'json-formatter' => $tool('json-formatter', 'JSON Formatter', 'developer', 'JSON 문자열을 보기 좋게 정렬하고 압축하며 문법 오류를 빠르게 확인합니다.', [
        'widget' => 'json-formatter',
        'is_popular' => true,
        'is_frequent' => true,
        'keywords' => ['JSON Formatter', 'JSON Pretty Print', 'JSON Minify', 'JSON Validator'],
        'related' => ['json-validator', 'json-csv', 'json-xml', 'jwt-decoder'],
        'how_to_use' => ['JSON 문자열을 입력합니다.', 'Format 버튼으로 들여쓰기 된 JSON을 확인합니다.', 'Minify 버튼으로 공백을 제거한 JSON을 만들 수 있습니다.'],
        'examples' => [['title' => 'API 응답 JSON 정리', 'input' => '{"name":"WY Tools","type":"free"}', 'output' => "JSON이 줄바꿈과 들여쓰기 형태로 정리됩니다."]],
        'faqs' => [['q' => '잘못된 JSON도 자동 수정하나요?', 'a' => '문법 오류는 알려주지만 데이터 의미를 추정해 자동 수정하지는 않습니다.'], ['q' => '입력한 JSON은 저장되나요?', 'a' => '아니요. 브라우저에서만 처리합니다.']],
    ]),
    'json-validator' => $tool('json-validator', 'JSON Validator', 'developer', 'JSON 문법이 유효한지 확인하고 오류를 찾습니다.', ['widget' => 'json-validator', 'is_recent' => true, 'keywords' => ['JSON Validator', 'JSON Syntax Checker'], 'related' => ['json-formatter', 'json-csv', 'json-xml']]),
    'base64' => $tool('base64', 'Base64 Encode / Decode', 'encoding', '텍스트와 한글 문자열을 Base64로 인코딩하거나 디코딩합니다.', [
        'widget' => 'base64',
        'is_popular' => true,
        'keywords' => ['Base64 Encode', 'Base64 Decode', 'Base64 변환'],
        'related' => ['url-encode', 'image-to-base64', 'jwt-decoder'],
        'how_to_use' => ['원본 텍스트나 Base64 문자열을 입력합니다.', 'Encode 또는 Decode 버튼을 선택합니다.', '결과를 복사해 필요한 곳에 사용합니다.'],
        'faqs' => [['q' => '한글도 Base64 변환이 되나요?', 'a' => '네. UTF-8 기준으로 한글도 변환합니다.'], ['q' => 'Base64는 암호화인가요?', 'a' => '아니요. 인코딩 방식이며 보안 목적의 암호화가 아닙니다.']],
    ]),
    'jwt-decoder' => $tool('jwt-decoder', 'JWT Decoder', 'developer', 'JWT 토큰의 header와 payload를 디코딩해 내용을 확인합니다.', ['widget' => 'jwt-decoder', 'is_recent' => true, 'keywords' => ['JWT Decoder', 'JWT Decode'], 'related' => ['base64', 'json-formatter', 'sha256']]),
    'uuid' => $tool('uuid', 'UUID Generator', 'developer', 'UUID v4 값을 브라우저에서 여러 개 즉시 생성합니다.', [
        'widget' => 'uuid',
        'is_popular' => true,
        'keywords' => ['UUID Generator', 'UUID v4', 'GUID Generator'],
        'related' => ['password-generator', 'hash-generator', 'jwt-decoder'],
    ]),
    'regex-tester' => $tool('regex-tester', 'Regex Tester', 'developer', '정규식을 테스트하고 매칭 결과를 확인합니다.', ['widget' => 'regex-tester', 'is_recent' => true, 'keywords' => ['Regex Tester', 'Regular Expression Test'], 'related' => ['word-counter', 'text-diff', 'remove-duplicate-lines']]),
    'sql-formatter' => $tool('sql-formatter', 'SQL Formatter', 'developer', 'SQL 쿼리를 읽기 좋은 형태로 정리합니다.', ['widget' => 'sql-formatter', 'keywords' => ['SQL Formatter', 'SQL Pretty Print'], 'related' => ['json-formatter', 'csv-viewer']]),
    'cron-generator' => $tool('cron-generator', 'Cron Generator', 'developer', 'Cron 표현식을 만들고 5필드 스케줄 의미를 확인합니다.', [
        'widget' => 'cron-helper',
        'keywords' => ['Cron Generator', 'Cron Expression', 'Crontab'],
        'related' => ['timestamp', 'date-calculator', 'd-day-calculator'],
    ]),
    'cron-helper' => $tool('cron-helper', 'Cron Expression Helper', 'developer', '5필드 Cron 표현식의 분, 시, 일, 월, 요일 의미를 해석합니다.', [
        'widget' => 'cron-helper',
        'related' => ['cron-generator', 'timestamp', 'date-calculator'],
    ]),

    'lorem-ipsum' => $tool('lorem-ipsum', 'Lorem Ipsum Generator', 'text', '디자인 시안과 문서 작업에 사용할 더미 텍스트를 생성합니다.', ['widget' => 'lorem-ipsum', 'is_recent' => true, 'related' => ['word-counter', 'case-converter']]),
    'word-counter' => $tool('word-counter', 'Word Counter', 'text', '글자 수, 단어 수, 줄 수를 계산합니다.', ['widget' => 'word-counter', 'is_popular' => true, 'related' => ['case-converter', 'remove-duplicate-lines', 'text-diff']]),
    'case-converter' => $tool('case-converter', 'Case Converter', 'text', '영문 텍스트를 대문자, 소문자, 제목 케이스 등으로 변환합니다.', ['widget' => 'case-converter', 'related' => ['word-counter', 'lorem-ipsum']]),
    'remove-duplicate-lines' => $tool('remove-duplicate-lines', 'Remove Duplicate Lines', 'text', '중복된 줄을 제거하고 고유한 목록만 남깁니다.', ['widget' => 'remove-duplicate-lines', 'related' => ['text-diff', 'word-counter']]),
    'text-diff' => $tool('text-diff', 'Text Diff', 'text', '두 텍스트의 차이를 비교합니다.', ['widget' => 'text-diff', 'related' => ['remove-duplicate-lines', 'regex-tester']]),
    'personal-info-masker' => $tool('personal-info-masker', '개인정보 마스킹 도구', 'text', '전화번호, 이메일, 주민등록번호 패턴을 찾아 일부를 마스킹합니다.', [
        'widget' => 'personal-info-masker',
        'is_recent' => true,
        'keywords' => ['개인정보 마스킹', '전화번호 마스킹', '이메일 마스킹', '주민번호 마스킹'],
        'related' => ['word-counter', 'regex-tester', 'text-diff'],
    ]),
    'random-picker' => $tool('random-picker', '랜덤 추첨기', 'text', '이름이나 항목 목록에서 무작위 당첨자를 추첨합니다.', [
        'widget' => 'random-picker',
        'is_popular' => true,
        'is_recent' => true,
        'keywords' => ['랜덤 추첨기', '이름 추첨기', '당첨자 뽑기'],
        'related' => ['list-shuffler', 'remove-duplicate-lines'],
    ]),
    'list-shuffler' => $tool('list-shuffler', '목록 셔플 도구', 'text', '줄 단위 목록을 무작위로 섞거나 번호를 붙여 정리합니다.', [
        'widget' => 'list-shuffler',
        'is_frequent' => true,
        'keywords' => ['목록 섞기', '랜덤 순서', '리스트 셔플'],
        'related' => ['random-picker', 'remove-duplicate-lines'],
    ]),
    'checklist-generator' => $tool('checklist-generator', '체크리스트 생성기', 'text', '줄 단위 메모를 Markdown 체크리스트로 변환합니다.', [
        'widget' => 'checklist-generator',
        'keywords' => ['체크리스트 생성기', 'Markdown 체크리스트', '할일 목록 변환'],
        'related' => ['note-cleaner', 'case-converter'],
    ]),
    'csv-sort-filter' => $tool('csv-sort-filter', 'CSV 정렬/필터 도구', 'text', 'CSV 데이터를 컬럼 기준으로 필터링하고 정렬합니다.', [
        'widget' => 'csv-sort-filter',
        'is_recent' => true,
        'keywords' => ['CSV 정렬', 'CSV 필터', 'CSV 데이터 정리'],
        'related' => ['csv-viewer', 'json-csv'],
    ]),
    'csv-column-mapper-compare' => $tool('csv-column-mapper-compare', 'CSV 컬럼 매핑·비교', 'text', '두 CSV 파일의 키 컬럼과 비교 컬럼을 매핑해 누락, 추가, 변경된 데이터를 브라우저에서 비교합니다.', [
        'widget' => 'csv-column-mapper-compare',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => 'CSV 컬럼 매핑·비교 - 두 CSV 중복·누락·변경값 확인 | WY Tools',
        'meta_description' => '두 CSV 파일의 키 컬럼과 비교 항목을 연결해 동일, 변경, 누락, 추가 데이터를 확인하고 비교 결과 CSV를 다운로드합니다. 파일은 브라우저에서만 처리됩니다.',
        'keywords' => ['CSV 비교', 'CSV 컬럼 매핑', 'CSV 중복 확인', 'CSV 누락 비교', 'CSV 변경 비교', '엑셀 CSV 비교'],
        'related' => ['csv-viewer', 'csv-sort-filter', 'json-csv', 'text-diff'],
        'how_to_use' => ['비교할 CSV A와 CSV B 파일을 선택하고 컬럼을 불러옵니다.', '각 파일에서 같은 데이터를 식별할 키 컬럼을 선택한 뒤 비교할 컬럼을 연결합니다.', '비교 결과에서 동일·변경·누락·추가 건수를 확인하고 결과 CSV를 내려받습니다.'],
        'examples' => [
            ['title' => '상품 목록 업데이트 확인', 'input' => 'CSV A 상품번호 / CSV B SKU를 키로 연결하고 가격·재고·상품명을 매핑', 'output' => '가격이나 재고가 바뀐 상품, 신규 상품, 삭제된 상품을 구분합니다.'],
            ['title' => '고객 데이터 정합성 점검', 'input' => '기존 고객 CSV와 새 고객 CSV의 이메일 또는 고객 ID를 키로 선택', 'output' => '누락·추가·변경된 고객 정보를 비교 결과 CSV로 저장합니다.'],
        ],
        'faqs' => [
            ['q' => 'CSV 파일은 서버에 업로드되나요?', 'a' => '아니요. 선택한 파일은 브라우저 안에서만 읽고 비교하며 서버로 전송하거나 저장하지 않습니다.'],
            ['q' => '서로 다른 컬럼 이름도 비교할 수 있나요?', 'a' => '네. 예를 들어 CSV A의 상품번호를 CSV B의 SKU와 키로 연결하고, 각 비교 항목도 원하는 컬럼끼리 매핑할 수 있습니다.'],
            ['q' => '무료 사용 한도는 어떻게 되나요?', 'a' => '현재는 안정적인 브라우저 처리를 위해 파일당 2MB, 데이터 행 10,000행까지 지원합니다. 대용량 처리와 저장 매핑은 향후 Pro 기능으로 검토합니다.'],
        ],
    ]),
    'excel-table-converter' => $tool('excel-table-converter', '엑셀 표 변환기', 'text', '엑셀에서 복사한 탭 구분 표를 Markdown, HTML, CSV로 변환합니다.', [
        'widget' => 'excel-table-converter',
        'keywords' => ['엑셀 표 변환', 'Markdown 표 변환', 'HTML 테이블 변환'],
        'related' => ['csv-viewer', 'csv-sort-filter'],
    ]),
    'note-cleaner' => $tool('note-cleaner', '메모 정리기', 'text', '흩어진 메모의 공백, 빈 줄, 중복 줄을 정리합니다.', [
        'widget' => 'note-cleaner',
        'is_frequent' => true,
        'keywords' => ['메모 정리', '텍스트 정리', '공백 제거'],
        'related' => ['checklist-generator', 'remove-duplicate-lines'],
    ]),
    'list-compare' => $tool('list-compare', '중복 데이터 비교 도구', 'text', 'A 목록과 B 목록을 비교해 공통, A에만 있음, B에만 있음을 분류합니다.', [
        'widget' => 'list-compare',
        'is_popular' => true,
        'is_recent' => true,
        'keywords' => ['중복 데이터 비교', '목록 비교', '리스트 비교'],
        'related' => ['remove-duplicate-lines', 'text-diff'],
    ]),
    'line-number-tool' => $tool('line-number-tool', '줄 번호 추가/제거 도구', 'text', '텍스트 줄 앞에 번호를 붙이거나 기존 줄 번호를 제거합니다.', [
        'widget' => 'line-number-tool',
        'keywords' => ['줄 번호 추가', '줄 번호 제거', '텍스트 번호 매기기'],
        'related' => ['note-cleaner', 'list-shuffler'],
    ]),
    'text-sorter' => $tool('text-sorter', '텍스트 정렬 도구', 'text', '줄 단위 텍스트를 가나다순, ABC순, 숫자순으로 정렬합니다.', [
        'widget' => 'text-sorter',
        'is_frequent' => true,
        'keywords' => ['텍스트 정렬', '가나다 정렬', '목록 정렬'],
        'related' => ['list-shuffler', 'remove-duplicate-lines'],
    ]),
    'table-transpose' => $tool('table-transpose', '표 행/열 전환 도구', 'text', '엑셀에서 복사한 표의 행과 열을 서로 전환합니다.', [
        'widget' => 'table-transpose',
        'keywords' => ['표 행열 전환', '엑셀 행열 바꾸기', '테이블 transpose'],
        'related' => ['excel-table-converter', 'csv-sort-filter'],
    ]),

    'image-compress' => $tool('image-compress', 'Image Compress', 'image', '이미지 용량을 줄여 웹 업로드와 공유에 적합하게 만듭니다.', ['widget' => 'image-processor', 'is_popular' => true, 'related' => ['image-resize', 'webp-converter']]),
    'image-resize' => $tool('image-resize', 'Image Resize', 'image', '이미지의 가로, 세로 크기를 조정합니다.', ['widget' => 'image-processor', 'related' => ['image-compress', 'image-crop']]),
    'image-crop' => $tool('image-crop', 'Image Crop', 'image', '이미지에서 필요한 영역만 잘라냅니다.', ['widget' => 'image-processor', 'related' => ['image-resize', 'webp-converter']]),
    'webp-converter' => $tool('webp-converter', 'WEBP Converter', 'image', '이미지를 WEBP 형식으로 변환해 웹 성능을 개선합니다.', ['widget' => 'image-processor', 'related' => ['image-compress', 'image-resize']]),
    'image-to-base64' => $tool('image-to-base64', 'Image to Base64', 'image', '이미지 파일을 Base64 문자열로 변환합니다.', ['widget' => 'image-base64', 'related' => ['base64', 'webp-converter']]),

    'merge-pdf' => $tool('merge-pdf', 'Merge PDF', 'pdf', '여러 PDF 파일을 하나의 문서로 합칩니다.', ['widget' => 'pdf-merge', 'is_popular' => true, 'related' => ['split-pdf', 'compress-pdf']]),
    'split-pdf' => $tool('split-pdf', 'Split PDF', 'pdf', 'PDF 문서를 페이지 단위로 분리합니다.', ['widget' => 'pdf-split', 'related' => ['merge-pdf', 'rotate-pdf']]),
    'compress-pdf' => $tool('compress-pdf', 'Compress PDF', 'pdf', 'PDF 파일 용량을 줄입니다.', ['widget' => 'pdf-compress', 'related' => ['merge-pdf', 'split-pdf']]),
    'rotate-pdf' => $tool('rotate-pdf', 'Rotate PDF', 'pdf', 'PDF 페이지 방향을 회전합니다.', ['widget' => 'pdf-rotate', 'related' => ['split-pdf', 'merge-pdf']]),
    'pdf-batch-processor' => $tool('pdf-batch-processor', 'PDF 일괄처리', 'pdf', '여러 PDF를 한 번에 병합, 개별 분할, 회전, 최적화하고 결과를 ZIP으로 내려받습니다.', [
        'widget' => 'pdf-batch',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => 'PDF 일괄처리 - 병합·분할·회전·최적화 ZIP 다운로드 | WY Tools',
        'meta_description' => '여러 PDF 파일을 브라우저에서 한 번에 병합, 페이지별 분할, 회전, 최적화하고 결과를 ZIP으로 다운로드하는 무료 PDF 일괄처리 도구입니다.',
        'keywords' => ['PDF 일괄처리', 'PDF 일괄 병합', 'PDF 일괄 분할', 'PDF 일괄 회전', 'PDF ZIP 다운로드', 'PDF 대량 처리'],
        'related' => ['merge-pdf', 'split-pdf', 'rotate-pdf', 'compress-pdf'],
        'how_to_use' => ['처리할 PDF를 최대 10개, 총 50MB까지 선택합니다.', '병합, 페이지별 분할, 회전, 최적화 중 원하는 작업을 선택합니다.', '처리 후 단일 PDF 또는 여러 결과가 담긴 ZIP 파일을 내려받습니다.'],
        'examples' => [
            ['title' => '여러 계약서 병합', 'input' => '계약서 PDF 5개 / 작업: 하나로 병합', 'output' => '선택한 순서대로 페이지를 합친 하나의 PDF를 다운로드합니다.'],
            ['title' => '스캔 문서 방향 일괄 수정', 'input' => '스캔 PDF 8개 / 작업: 90도 회전', 'output' => '각 파일을 회전 처리한 결과를 ZIP 파일로 다운로드합니다.'],
        ],
        'faqs' => [
            ['q' => 'PDF 파일은 서버로 업로드되나요?', 'a' => '아니요. 모든 처리는 브라우저에서 이뤄지며 파일은 서버로 전송하거나 저장하지 않습니다.'],
            ['q' => '무료 사용 한도는 어떻게 되나요?', 'a' => '안정적인 브라우저 처리를 위해 한 번에 최대 10개 파일, 총 50MB까지 지원합니다. 더 큰 작업과 작업 프리셋은 향후 Pro 기능으로 검토합니다.'],
            ['q' => '최적화는 이미지 품질을 낮추나요?', 'a' => '현재 최적화는 PDF를 재저장해 구조를 정리하는 방식입니다. 스캔 이미지가 많은 PDF는 파일 크기가 크게 줄지 않을 수 있습니다.'],
        ],
    ]),

    'json-csv' => $tool('json-csv', 'JSON to CSV Converter', 'converter', 'JSON 데이터를 CSV 형식으로 변환합니다.', ['widget' => 'json-csv', 'related' => ['json-formatter', 'csv-viewer', 'json-xml']]),
    'json-xml' => $tool('json-xml', 'JSON to XML Converter', 'converter', 'JSON과 XML 데이터를 상호 변환합니다.', ['widget' => 'json-xml', 'related' => ['json-formatter', 'json-csv']]),
    'csv-viewer' => $tool('csv-viewer', 'CSV Viewer', 'converter', 'CSV 데이터를 표 형태로 확인합니다.', ['widget' => 'csv-viewer', 'related' => ['json-csv', 'sql-formatter']]),
    'timestamp' => $tool('timestamp', 'Timestamp Converter', 'date-time', 'Unix timestamp를 로컬 시간과 UTC 날짜로 변환합니다.', [
        'widget' => 'timestamp',
        'is_popular' => true,
        'keywords' => ['Unix Timestamp Converter', 'Epoch Time', 'Timestamp 변환'],
        'related' => ['cron-generator', 'date-calculator', 'd-day-calculator'],
    ]),

    'password-generator' => $tool('password-generator', 'Password Generator', 'security', '길이와 문자 옵션을 선택해 임시 비밀번호를 생성합니다.', [
        'widget' => 'password-generator',
        'is_popular' => true,
        'is_frequent' => true,
        'related' => ['uuid', 'sha256', 'bcrypt'],
    ]),
    'sha256' => $tool('sha256', 'SHA256 Generator', 'security', '텍스트를 SHA-256 해시 값으로 변환합니다.', ['widget' => 'hash-generator', 'related' => ['hash-generator', 'md5', 'bcrypt']]),
    'md5' => $tool('md5', 'MD5 Generator', 'security', '텍스트의 MD5 해시 값을 생성합니다.', ['widget' => 'md5', 'related' => ['sha256', 'hash-generator']]),
    'bcrypt' => $tool('bcrypt', 'bcrypt Hash Generator', 'security', '비밀번호 저장에 자주 쓰이는 bcrypt 해시를 생성합니다.', ['widget' => 'bcrypt-helper', 'related' => ['password-generator', 'sha256']]),
    'hash-generator' => $tool('hash-generator', 'Hash Generator', 'security', '텍스트를 SHA-1, SHA-256, SHA-384, SHA-512 해시 값으로 변환합니다.', [
        'widget' => 'hash-generator',
        'related' => ['sha256', 'md5', 'password-generator'],
    ]),

    'vat-calculator' => $tool('vat-calculator', 'VAT 계산기', 'calculator', '공급가액과 부가세, 합계 금액을 계산합니다.', [
        'widget' => 'vat-calculator',
        'is_recent' => true,
        'meta_title' => '부가세 계산기 - 공급가액·부가세·합계 금액 계산 | WY Tools',
        'meta_description' => '공급가액에서 부가세와 합계 금액을 계산하거나, 합계 금액에서 공급가액과 부가세를 역산하는 무료 부가세 계산기입니다.',
        'keywords' => ['부가세 계산기', 'VAT 계산기', '공급가액 계산기', '세금계산서 부가세 계산'],
        'related' => ['percent-calculator', 'margin-calculator', 'shipping-margin-calculator'],
        'how_to_use' => [
            '공급가액을 알고 있다면 금액을 입력한 뒤 공급가액 기준 계산을 선택합니다.',
            '결제 총액만 알고 있다면 합계 금액 기준 계산을 선택해 공급가액과 부가세를 역산합니다.',
            '계산된 공급가액, 부가세, 합계 금액을 견적서나 세금계산서 작성 전에 확인합니다.',
        ],
        'examples' => [
            ['title' => '공급가액 100,000원 계산', 'input' => '공급가액 100,000원', 'output' => '부가세 10,000원, 합계 금액 110,000원'],
            ['title' => '합계 금액 110,000원 역산', 'input' => '합계 금액 110,000원', 'output' => '공급가액 100,000원, 부가세 10,000원'],
        ],
        'faqs' => [
            ['q' => '부가세율은 몇 퍼센트로 계산하나요?', 'a' => '일반적인 국내 부가가치세율 10% 기준으로 계산합니다. 면세, 영세율, 업종별 예외는 별도로 확인해야 합니다.'],
            ['q' => '공급가액과 합계 금액의 차이는 무엇인가요?', 'a' => '공급가액은 부가세를 제외한 금액이고, 합계 금액은 공급가액에 부가세를 더한 최종 금액입니다.'],
            ['q' => '세금계산서 발행 금액으로 바로 사용해도 되나요?', 'a' => '간편 계산용으로 사용할 수 있지만, 실제 발행 전에는 거래 조건과 회계 처리 기준을 함께 확인하는 것이 좋습니다.'],
        ],
    ]),
    'percent-calculator' => $tool('percent-calculator', '퍼센트 계산기', 'calculator', '비율, 증감률, 할인율을 계산합니다.', [
        'widget' => 'percent-calculator',
        'is_popular' => true,
        'meta_title' => '퍼센트 계산기 - 비율·증감률·할인율 계산 | WY Tools',
        'meta_description' => '전체 대비 비율, 증가율과 감소율, 할인율을 빠르게 계산하는 무료 퍼센트 계산기입니다.',
        'keywords' => ['퍼센트 계산기', '비율 계산기', '증감률 계산기', '할인율 계산기'],
        'related' => ['vat-calculator', 'margin-calculator', 'loan-calculator'],
    ]),
    'withholding-3-3-calculator' => $tool('withholding-3-3-calculator', '3.3% 계산기', 'calculator', '프리랜서·사업소득 3.3% 원천징수액과 실수령액을 계산합니다.', [
        'widget' => 'withholding-3-3',
        'is_popular' => true,
        'is_recent' => true,
        'is_frequent' => true,
        'meta_title' => '3.3% 계산기 - 프리랜서 원천징수·실수령액 계산 | WY Tools',
        'meta_description' => '프리랜서와 사업소득자의 3.3% 원천징수 세액, 계약금액, 실수령액을 간편하게 계산합니다.',
        'keywords' => ['3.3% 계산기', '프리랜서 세금 계산기', '원천징수 계산기', '실수령액 계산기'],
        'related' => ['vat-calculator', 'percent-calculator', 'salary-calculator'],
        'how_to_use' => [
            '계약금액 기준으로 계산할지, 실수령액 기준으로 역산할지 선택합니다.',
            '금액을 입력하면 3.3% 원천징수액과 지급액을 확인할 수 있습니다.',
            '계약서, 견적서, 정산서에 적을 금액을 비교해 봅니다.',
        ],
        'examples' => [
            ['title' => '계약금액 1,000,000원', 'input' => '총 지급액 1,000,000원', 'output' => '원천징수 33,000원, 실수령액 967,000원'],
            ['title' => '실수령액 967,000원 역산', 'input' => '받고 싶은 금액 967,000원', 'output' => '계약금액 약 1,000,000원, 원천징수액 약 33,000원'],
        ],
        'faqs' => [
            ['q' => '3.3%는 무엇인가요?', 'a' => '일반적으로 사업소득 원천징수 3%와 지방소득세 0.3%를 합친 비율입니다.'],
            ['q' => '프리랜서는 항상 3.3%를 떼나요?', 'a' => '계약 형태와 소득 구분에 따라 달라질 수 있습니다. 사업소득으로 처리되는 경우에 주로 3.3% 원천징수가 적용됩니다.'],
            ['q' => '실제 종합소득세와 같은 금액인가요?', 'a' => '아닙니다. 3.3%는 지급 시점의 원천징수액이고, 최종 세금은 종합소득세 신고 때 소득과 공제에 따라 달라질 수 있습니다.'],
        ],
    ]),
    'salary-calculator' => $tool('salary-calculator', '시급·월급 환산기', 'calculator', '시급, 근무시간, 근무일 기준으로 월급과 연봉을 빠르게 환산합니다.', [
        'widget' => 'salary-calculator',
        'is_recent' => true,
        'meta_title' => '시급·월급 계산기 - 월급·연봉 환산 계산 | WY Tools',
        'meta_description' => '시급, 근무시간, 근무일을 기준으로 예상 월급과 연봉을 환산하는 무료 급여 계산기입니다.',
        'keywords' => ['시급 계산기', '월급 계산기', '연봉 계산기', '급여 환산기'],
        'related' => ['withholding-3-3-calculator', 'percent-calculator'],
    ]),
    'annual-salary-net-calculator' => $tool('annual-salary-net-calculator', '연봉 실수령액 계산기', 'calculator', '연봉 기준 월 예상 실수령액과 공제액을 계산합니다.', [
        'widget' => 'annual-salary-net',
        'is_popular' => true,
        'is_recent' => true,
        'meta_title' => '연봉 실수령액 계산기 - 월급 실수령액·공제액 계산 | WY Tools',
        'meta_description' => '연봉을 입력해 월 예상 실수령액과 국민연금, 건강보험, 고용보험, 소득세 등 공제액을 간편 계산합니다.',
        'keywords' => ['연봉 실수령액 계산기', '월급 실수령액', '4대보험 계산기'],
        'related' => ['salary-calculator', 'withholding-3-3-calculator', 'weekly-holiday-pay-calculator'],
        'how_to_use' => [
            '연봉을 세전 금액 기준으로 입력합니다.',
            '월 소득세나 별도 공제액을 알고 있다면 입력값을 조정합니다.',
            '월 예상 지급액과 공제 합계를 확인해 이직, 연봉 협상, 예산 계획에 참고합니다.',
        ],
        'examples' => [
            ['title' => '연봉 50,000,000원 예시', 'input' => '세전 연봉 50,000,000원', 'output' => '월 세전 약 4,166,667원에서 4대보험과 세금을 제외한 예상 실수령액을 계산합니다.'],
            ['title' => '연봉 협상 비교', 'input' => '현재 연봉과 제안 연봉을 각각 입력', 'output' => '월 실수령액 차이를 확인해 실제 체감 인상액을 비교합니다.'],
        ],
        'faqs' => [
            ['q' => '연봉 실수령액은 정확한 금액인가요?', 'a' => '예상 계산값입니다. 실제 공제액은 부양가족, 비과세 항목, 회사 공제 기준, 보험료율에 따라 달라질 수 있습니다.'],
            ['q' => '세전 연봉과 세후 연봉은 무엇이 다른가요?', 'a' => '세전 연봉은 공제 전 계약 금액이고, 세후 또는 실수령액은 4대보험과 세금 등을 제외하고 실제 받는 금액입니다.'],
            ['q' => '월급 실수령액 비교에도 사용할 수 있나요?', 'a' => '네. 연봉 기준 월 예상 실수령액을 확인해 이직 제안이나 연봉 협상 조건을 비교하는 데 사용할 수 있습니다.'],
        ],
    ]),
    'weekly-holiday-pay-calculator' => $tool('weekly-holiday-pay-calculator', '주휴수당 계산기', 'calculator', '시급과 주 근무시간으로 주휴수당과 주급을 계산합니다.', [
        'widget' => 'weekly-holiday-pay',
        'is_frequent' => true,
        'meta_title' => '주휴수당 계산기 - 알바 주급·시급 기준 주휴수당 계산 | WY Tools',
        'meta_description' => '시급과 주 근무시간을 입력해 예상 주휴수당, 주급, 총 지급액을 계산하는 무료 주휴수당 계산기입니다.',
        'keywords' => ['주휴수당 계산기', '알바 주휴수당', '시급 주급 계산기'],
        'related' => ['salary-calculator', 'annual-salary-net-calculator'],
        'how_to_use' => [
            '시급과 1주 근무시간을 입력합니다.',
            '주휴수당 계산 버튼을 눌러 주휴시간과 주휴수당을 확인합니다.',
            '주급 총액과 비교해 아르바이트 급여 정산에 참고합니다.',
        ],
        'examples' => [
            ['title' => '시급 10,030원, 주 40시간', 'input' => '시급 10,030원 / 주 40시간 근무', 'output' => '주휴시간 8시간 기준 주휴수당과 주급 총액을 계산합니다.'],
            ['title' => '주 20시간 근무', 'input' => '시급과 주 20시간 입력', 'output' => '근무시간 비율에 따른 예상 주휴수당을 확인합니다.'],
        ],
        'faqs' => [
            ['q' => '주휴수당은 언제 받을 수 있나요?', 'a' => '일반적으로 소정근로시간과 개근 요건을 충족하는 경우 발생합니다. 실제 적용은 근로계약과 근무 형태를 확인해야 합니다.'],
            ['q' => '주 15시간 미만도 주휴수당이 있나요?', 'a' => '일반적으로 주 15시간 미만 근무자는 주휴수당 적용 대상이 아닐 수 있습니다. 정확한 판단은 근로 조건을 기준으로 확인해야 합니다.'],
            ['q' => '최저시급이 바뀌면 어떻게 하나요?', 'a' => '해당 연도의 시급을 직접 입력해 계산하면 됩니다. 이 도구는 입력한 시급을 기준으로 계산합니다.'],
        ],
    ]),
    'severance-pay-calculator' => $tool('severance-pay-calculator', '퇴직금 계산기', 'calculator', '평균임금과 재직기간으로 예상 퇴직금을 계산합니다.', [
        'widget' => 'severance-pay',
        'meta_title' => '퇴직금 계산기 - 평균임금·재직기간 기준 퇴직급여 계산 | WY Tools',
        'meta_description' => '평균임금과 재직기간을 기준으로 예상 퇴직금과 재직연수를 계산하는 무료 퇴직금 계산기입니다.',
        'keywords' => ['퇴직금 계산기', '퇴직급여 계산기', '평균임금 계산'],
        'related' => ['annual-salary-net-calculator', 'salary-calculator'],
        'how_to_use' => [
            '최근 임금 기준으로 계산한 평균 일급을 입력합니다.',
            '입사일부터 퇴사일까지의 재직일수를 입력합니다.',
            '예상 퇴직금과 재직연수를 확인해 퇴직 정산 전 참고합니다.',
        ],
        'examples' => [
            ['title' => '평균 일급 120,000원, 3년 근무', 'input' => '평균 일급 120,000원 / 재직일수 1,095일', 'output' => '30일분 평균임금과 재직연수 기준 예상 퇴직금을 계산합니다.'],
            ['title' => '퇴사 전 예상 정산', 'input' => '예상 평균 일급과 현재까지 재직일수 입력', 'output' => '퇴사 시점에 받을 수 있는 대략적인 퇴직금을 확인합니다.'],
        ],
        'faqs' => [
            ['q' => '퇴직금 계산식은 어떻게 보나요?', 'a' => '일반적으로 평균임금 30일분에 재직연수를 곱하는 방식으로 계산합니다. 회사 규정이나 퇴직연금 유형에 따라 차이가 있을 수 있습니다.'],
            ['q' => '1년 미만 근무도 퇴직금이 있나요?', 'a' => '일반적으로 계속근로기간 1년 이상 요건이 중요합니다. 근무 형태와 계약 조건에 따라 확인이 필요합니다.'],
            ['q' => '세전 금액인가요?', 'a' => '이 도구는 예상 퇴직급여를 간편 계산하는 용도이며, 실제 지급 시 세금과 정산 항목이 반영될 수 있습니다.'],
        ],
    ]),
    'margin-calculator' => $tool('margin-calculator', '마진율 계산기', 'calculator', '원가, 판매가, 수수료를 기준으로 마진과 마진율을 계산합니다.', [
        'widget' => 'margin-calculator',
        'is_popular' => true,
        'meta_title' => '마진율 계산기 - 원가·판매가·수수료 기준 마진 계산 | WY Tools',
        'meta_description' => '원가, 판매가, 판매 수수료를 입력해 순이익, 마진율, 마크업률을 계산하는 쇼핑몰 마진율 계산기입니다.',
        'keywords' => ['마진율 계산기', '원가 계산기', '판매가 계산기', '쇼핑몰 마진 계산'],
        'related' => ['shipping-margin-calculator', 'percent-calculator', 'vat-calculator'],
        'how_to_use' => [
            '상품 원가와 판매가를 입력합니다.',
            '오픈마켓, PG, 플랫폼 수수료가 있다면 수수료율을 입력합니다.',
            '순이익, 마진율, 마크업률을 확인해 가격 정책을 조정합니다.',
        ],
        'examples' => [
            ['title' => '원가 7,000원, 판매가 10,000원', 'input' => '원가 7,000원 / 판매가 10,000원 / 수수료 0%', 'output' => '이익 3,000원, 마진율 30%, 마크업률 약 42.9%'],
            ['title' => '판매 수수료 포함 계산', 'input' => '원가 15,000원 / 판매가 30,000원 / 수수료 3%', 'output' => '수수료 차감 후 실제 이익과 마진율을 계산합니다.'],
        ],
        'faqs' => [
            ['q' => '마진율과 마크업률은 무엇이 다른가요?', 'a' => '마진율은 판매가 대비 이익 비율이고, 마크업률은 원가 대비 이익 비율입니다. 같은 상품도 두 비율은 다르게 나옵니다.'],
            ['q' => '쇼핑몰 판매가 결정에 사용할 수 있나요?', 'a' => '네. 원가와 판매 수수료를 반영해 최소 판매가와 목표 마진을 검토하는 데 사용할 수 있습니다.'],
            ['q' => '배송비와 광고비까지 반영하려면 어떻게 하나요?', 'a' => '배송비 포함 마진 계산기를 함께 사용하면 배송비, 광고비, 추가 비용까지 반영한 실제 마진을 볼 수 있습니다.'],
        ],
    ]),
    'pyeong-calculator' => $tool('pyeong-calculator', '평수 계산기', 'calculator', '제곱미터와 평을 서로 변환하고 면적을 계산합니다.', [
        'widget' => 'pyeong-calculator',
        'is_frequent' => true,
        'keywords' => ['평수 계산기', '제곱미터 평 변환', '아파트 평수 계산'],
        'related' => ['unit-converter', 'date-calculator'],
    ]),
    'loan-calculator' => $tool('loan-calculator', '대출 이자 계산기', 'calculator', '원금, 금리, 기간으로 월 상환액과 총 이자를 계산합니다.', [
        'widget' => 'loan-calculator',
        'is_popular' => true,
        'meta_title' => '대출 이자 계산기 - 월 상환액·총 이자 계산 | WY Tools',
        'meta_description' => '대출 원금, 금리, 기간을 입력해 월 상환액과 총 이자를 계산하는 무료 대출 이자 계산기입니다.',
        'keywords' => ['대출 이자 계산기', '월 상환액 계산기', '원리금균등 계산기'],
        'related' => ['compound-interest-calculator', 'percent-calculator'],
        'how_to_use' => [
            '대출 원금, 연이율, 상환 기간을 입력합니다.',
            '계산 버튼을 눌러 월 예상 상환액과 총 이자를 확인합니다.',
            '금리나 기간을 바꿔 월 부담액이 어떻게 달라지는지 비교합니다.',
        ],
        'examples' => [
            ['title' => '1,000만원, 연 5%, 36개월', 'input' => '원금 10,000,000원 / 금리 5% / 기간 36개월', 'output' => '월 예상 상환액과 3년간 총 이자를 계산합니다.'],
            ['title' => '금리 비교', 'input' => '같은 원금과 기간에서 금리 4%, 5%, 6%를 각각 입력', 'output' => '금리 차이에 따른 월 상환액과 총 이자 차이를 비교합니다.'],
        ],
        'faqs' => [
            ['q' => '상환 방식은 무엇을 기준으로 하나요?', 'a' => '월 상환액을 추정하는 간편 계산 방식입니다. 실제 상품의 원리금균등, 원금균등, 만기일시 조건에 따라 결과가 달라질 수 있습니다.'],
            ['q' => '대출 금리는 연이율로 입력하나요?', 'a' => '네. 일반적으로 금융상품에 표시되는 연이율을 입력하면 월 기준으로 환산해 계산합니다.'],
            ['q' => '중도상환수수료도 포함되나요?', 'a' => '아니요. 이 도구는 원금, 금리, 기간 기준의 기본 이자 계산용이며 중도상환수수료, 보증료, 인지세 등은 별도로 확인해야 합니다.'],
        ],
    ]),
    'compound-interest-calculator' => $tool('compound-interest-calculator', '복리 계산기', 'calculator', '초기 금액, 추가 납입, 수익률 기준으로 미래 가치를 계산합니다.', [
        'widget' => 'compound-interest',
        'keywords' => ['복리 계산기', '투자 수익률 계산기', '미래가치 계산기'],
        'related' => ['loan-calculator', 'percent-calculator'],
    ]),
    'split-bill-calculator' => $tool('split-bill-calculator', '더치페이 계산기', 'calculator', '총액, 인원, 팁 또는 추가 비용을 기준으로 1인 부담액을 계산합니다.', [
        'widget' => 'split-bill',
        'is_frequent' => true,
        'keywords' => ['더치페이 계산기', 'N분의1 계산기', '회식비 계산기'],
        'related' => ['percent-calculator', 'vat-calculator'],
    ]),
    'shipping-margin-calculator' => $tool('shipping-margin-calculator', '배송비 포함 마진 계산기', 'calculator', '원가, 판매가, 배송비, 수수료를 반영해 실제 마진을 계산합니다.', [
        'widget' => 'shipping-margin',
        'is_recent' => true,
        'meta_title' => '배송비 포함 마진 계산기 - 쇼핑몰 실제 마진율 계산 | WY Tools',
        'meta_description' => '상품 원가, 판매가, 배송비, 판매 수수료, 광고비를 반영해 쇼핑몰 실제 마진과 손익분기 판매가를 계산합니다.',
        'keywords' => ['배송비 포함 마진 계산기', '쇼핑몰 마진 계산', '택배비 마진 계산'],
        'related' => ['margin-calculator', 'vat-calculator'],
        'how_to_use' => [
            '판매가와 상품 원가를 입력합니다.',
            '배송비, 플랫폼 수수료율, 광고비 등 추가 비용을 입력합니다.',
            '실제 이익, 마진율, 손익분기 판매가를 확인해 판매가를 조정합니다.',
        ],
        'examples' => [
            ['title' => '판매가 30,000원 상품', 'input' => '판매가 30,000원 / 원가 15,000원 / 배송비 3,000원 / 수수료 3%', 'output' => '배송비와 수수료 차감 후 실제 이익과 마진율을 계산합니다.'],
            ['title' => '광고비 포함 손익분기', 'input' => '상품당 광고비 2,000원을 추가 입력', 'output' => '광고비까지 반영한 순이익과 손익분기 판매가를 확인합니다.'],
        ],
        'faqs' => [
            ['q' => '일반 마진율 계산기와 무엇이 다른가요?', 'a' => '일반 마진율은 원가와 판매가 중심이고, 이 도구는 배송비, 수수료, 광고비처럼 실제 판매에서 빠지는 비용을 함께 반영합니다.'],
            ['q' => '무료배송 상품에도 사용할 수 있나요?', 'a' => '네. 판매자가 부담하는 배송비를 입력하면 무료배송 상품의 실제 마진을 계산할 수 있습니다.'],
            ['q' => '손익분기 판매가는 어떤 의미인가요?', 'a' => '입력한 비용을 모두 반영했을 때 이익이 0원이 되는 최소 판매가를 의미합니다. 목표 마진을 정할 때 기준점으로 사용할 수 있습니다.'],
        ],
    ]),
    'integrated-selling-margin-calculator' => $tool('integrated-selling-margin-calculator', '통합 판매 마진 계산기', 'calculator', '판매가, 원가, 플랫폼·결제 수수료, 배송비, 광고비, 부가세까지 반영해 온라인 판매의 실제 순이익을 계산합니다.', [
        'widget' => 'integrated-selling-margin',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => '통합 판매 마진 계산기 - 수수료·배송비·광고비·부가세 포함 | WY Tools',
        'meta_description' => '스마트스토어·쿠팡·오픈마켓 셀러를 위한 통합 판매 마진 계산기입니다. 판매가, 원가, 플랫폼·결제 수수료, 배송비, 포장비, 광고비와 부가세를 반영해 순이익·손익분기 판매가·목표 판매가를 계산합니다.',
        'keywords' => ['통합 판매 마진 계산기', '쇼핑몰 마진 계산기', '스마트스토어 마진 계산기', '쿠팡 마진 계산기', '오픈마켓 수수료 계산', '부가세 포함 마진 계산기'],
        'related' => ['shipping-margin-calculator', 'margin-calculator', 'vat-calculator', 'percent-calculator'],
        'how_to_use' => [
            '상품 판매가와 고객에게 별도로 받는 배송비를 입력합니다.',
            '상품 원가, 판매자 부담 배송비, 포장비, 주문당 광고비와 플랫폼·결제 수수료율을 입력합니다.',
            '부가세 포함 금액 기준으로 순이익, 마진율, 손익분기 및 목표 판매가를 확인합니다.',
        ],
        'examples' => [
            ['title' => '무료배송 상품의 실제 수익', 'input' => '판매가 29,900원 / 원가 12,000원 / 판매자 배송비 3,000원 / 플랫폼 8% / 결제 3% / 광고비 2,000원', 'output' => '모든 비용과 부가세를 반영한 주문당 예상 순이익과 손익분기 판매가를 확인합니다.'],
            ['title' => '유료배송 상품의 목표 판매가', 'input' => '판매가 19,900원 / 고객 배송비 3,000원 / 목표 순이익률 20%', 'output' => '입력한 비용 구조에서 목표 순이익률을 확보하는 최소 판매가를 계산합니다.'],
        ],
        'faqs' => [
            ['q' => '부가세는 어떻게 계산하나요?', 'a' => '모든 입력 금액이 부가세 포함 과세 금액이라는 가정으로 매출 부가세와 매입세액을 단순 추정합니다. 면세 상품, 간이과세, 공제 불가 항목 등은 실제 신고 결과와 다를 수 있습니다.'],
            ['q' => '플랫폼 수수료와 결제 수수료는 무엇을 기준으로 입력하나요?', 'a' => '상품 판매가와 고객 배송비의 합계 결제금액을 기준으로 각각 계산합니다. 플랫폼별 정산 정책과 부가 서비스 수수료는 별도로 확인해 합산해 주세요.'],
            ['q' => '결과를 실제 세금 신고에 사용해도 되나요?', 'a' => '아니요. 가격 정책을 검토하는 간편 계산 도구입니다. 실제 정산·부가세 신고는 플랫폼 정산서와 세무 전문가의 안내를 기준으로 확인해야 합니다.'],
        ],
    ]),
    'quote-amount-designer' => $tool('quote-amount-designer', '견적서 금액 설계기', 'calculator', '공급가, 부가세, 원천징수, 프로젝트 원가와 목표 마진을 함께 계산하고 PDF 견적서 초안을 만듭니다.', [
        'widget' => 'quote-amount-designer',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => '견적서 금액 설계기 - 공급가·VAT·원천징수·마진 계산 | WY Tools',
        'meta_description' => '프리랜서와 1인 사업자를 위한 견적서 금액 설계기입니다. 공급가액, 부가세, 3.3% 원천징수, 프로젝트 원가, 목표 마진을 계산하고 PDF로 저장 가능한 견적서 초안을 만듭니다.',
        'keywords' => ['견적서 계산기', '견적서 금액 계산', '공급가액 부가세 계산', '프리랜서 견적서', '3.3 원천징수 계산', '견적서 PDF'],
        'related' => ['vat-calculator', 'withholding-3-3-calculator', 'margin-calculator', 'integrated-selling-margin-calculator'],
        'how_to_use' => [
            '견적명, 고객명, 공급가액을 입력하고 부가세율과 원천징수율을 확인합니다.',
            '프로젝트 수행에 드는 직접 원가와 기타 비용, 목표 마진율을 입력합니다.',
            '견적 합계와 예상 수령액, 프로젝트 이익을 확인한 뒤 PDF 초안 버튼으로 인쇄 창을 엽니다.',
        ],
        'examples' => [
            ['title' => '웹사이트 제작 견적', 'input' => '공급가 2,000,000원 / VAT 10% / 직접 원가 800,000원 / 기타 비용 200,000원', 'output' => '견적 합계 2,200,000원, 프로젝트 이익 1,000,000원과 목표 마진 기준 최소 공급가를 확인합니다.'],
            ['title' => '3.3% 원천징수 대상 프리랜서 견적', 'input' => '공급가 500,000원 / 원천징수 3.3%', 'output' => '발주처 지급 시 원천징수되는 예상 금액과 실제 입금 예상액을 별도로 보여 줍니다.'],
        ],
        'faqs' => [
            ['q' => '원천징수 3.3%는 마진 비용인가요?', 'a' => '아니요. 일반적으로 원천징수는 소득세 선납 성격이므로 프로젝트 원가나 마진 계산에서는 별도 비용으로 빼지 않습니다. 이 도구는 입금 예상액을 확인하는 용도로 분리해 보여 줍니다.'],
            ['q' => 'PDF 파일이 바로 만들어지나요?', 'a' => 'PDF 초안 버튼을 누르면 브라우저 인쇄 창이 열립니다. 인쇄 대상에서 PDF로 저장을 선택하면 파일로 보관할 수 있습니다.'],
            ['q' => '실제 세금계산서나 계약서로 사용할 수 있나요?', 'a' => '금액 검토와 초안 작성용 도구입니다. 실제 발행 전에는 사업자 유형, 계약 조건, 면세 여부와 세무 기준을 확인해야 합니다.'],
        ],
    ]),
    'website-scope-estimator' => $tool('website-scope-estimator', '웹사이트 견적 범위 생성기', 'calculator', '웹사이트 유형, 페이지 수, 기능, 운영 기간을 선택해 개발 범위와 예상 견적 구간, 상담 문의 요약을 생성합니다.', [
        'widget' => 'website-scope-estimator',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => '웹사이트 견적 범위 생성기 - 홈페이지 제작 비용·기능 범위 계산 | WY Tools',
        'meta_description' => '홈페이지·쇼핑몰·회원 시스템·행사 사이트의 유형, 페이지 수, 기능, 운영 기간을 선택해 예상 개발 견적 범위와 일정, 상담 문의 요약을 생성합니다.',
        'keywords' => ['홈페이지 제작 견적', '웹사이트 견적 계산기', '웹사이트 개발 비용', '쇼핑몰 제작 비용', '홈페이지 제작 견적서', '웹사이트 기능 범위'],
        'related' => ['quote-amount-designer', 'integrated-selling-margin-calculator', 'vat-calculator'],
        'how_to_use' => [
            '만들려는 웹사이트 유형과 예상 페이지 수를 선택합니다.',
            '회원, 결제, 예약, 외부 연동 등 필요한 기능과 운영 기간을 체크합니다.',
            '예상 견적·일정 범위와 생성된 문의 요약을 검토한 뒤 상담 시 활용합니다.',
        ],
        'examples' => [
            ['title' => '기업 홈페이지 구축', 'input' => '기업 홈페이지 / 10페이지 / 문의폼·관리자·다국어', 'output' => '기본 사이트, 추가 페이지, 선택 기능을 합산한 개발비와 예상 일정 구간을 확인합니다.'],
            ['title' => '회원·결제 서비스', 'input' => '회원 서비스 / 15페이지 / 회원가입·결제·관리자·외부 API', 'output' => '기능 복잡도를 반영한 상담용 개발 범위와 문의 요약문을 생성합니다.'],
        ],
        'faqs' => [
            ['q' => '표시되는 금액이 확정 견적인가요?', 'a' => '아니요. 요구사항을 빠르게 정리하기 위한 사전 범위입니다. 디자인 수준, 콘텐츠 준비 상태, 연동 API, 보안·인프라 요구에 따라 실제 견적은 달라집니다.'],
            ['q' => '운영 기간 비용에는 무엇이 포함되나요?', 'a' => '기본 유지보수·운영 지원의 월 예상 범위입니다. 서버·도메인·유료 솔루션·광고비·대규모 콘텐츠 작업은 별도 협의가 필요합니다.'],
            ['q' => '생성된 문의 요약은 어디에 쓰나요?', 'a' => '복사 버튼으로 상담 문의, 이메일 또는 내부 기획 문서에 붙여 넣어 초기 요구사항 전달에 사용할 수 있습니다.'],
        ],
    ]),
    'freelancer-cashflow-planner' => $tool('freelancer-cashflow-planner', '프리랜서 현금흐름 플래너', 'calculator', '월 매출, 사업비, 생활비, 세금 적립, 저축을 반영해 실제 가용 현금과 다음 달 목표 매출을 계산합니다.', [
        'widget' => 'freelancer-cashflow-planner',
        'is_recent' => true,
        'premium_ready' => true,
        'meta_title' => '프리랜서 현금흐름 플래너 - 월 가용 현금·세금 적립·목표 매출 계산 | WY Tools',
        'meta_description' => '프리랜서와 1인 사업자를 위한 월 현금흐름 계산기입니다. 매출, 사업비, 생활비, 부가세·종합소득세 적립액, 저축을 반영해 월말 가용 현금과 다음 달 목표 매출을 계산합니다.',
        'keywords' => ['프리랜서 현금흐름', '프리랜서 월 수입 계산', '1인 사업자 현금흐름', '세금 적립 계산기', '프리랜서 목표 매출'],
        'related' => ['quote-amount-designer', 'withholding-3-3-calculator', 'vat-calculator', 'integrated-selling-margin-calculator'],
        'how_to_use' => [
            '이번 달 입금 예정 매출과 기타 수입, 월초 보유 현금을 입력합니다.',
            '사업 고정비·변동비, 생활비, 대출·카드 상환, 저축 목표를 입력합니다.',
            '세금 적립률을 설정해 월말 예상 현금과 다음 달 목표 매출을 확인합니다.',
        ],
        'examples' => [
            ['title' => '월 매출 500만원 프리랜서', 'input' => '매출 5,000,000원 / 사업비 800,000원 / 생활비 1,500,000원 / 세금 적립률 20%', 'output' => '세금과 비용을 미리 떼어 둔 뒤 실제 가용 현금과 다음 달 필요 매출을 확인합니다.'],
            ['title' => '수입이 불규칙한 달', 'input' => '월초 현금 2,000,000원 / 입금 예정 매출 2,500,000원 / 목표 저축 500,000원', 'output' => '월말 예상 잔액과 현재 현금으로 버틸 수 있는 기간을 점검합니다.'],
        ],
        'faqs' => [
            ['q' => '원천징수 3.3%와 세금 적립은 어떻게 다른가요?', 'a' => '원천징수는 이미 선납된 세금이고, 세금 적립은 향후 부가세·종합소득세 납부를 대비해 별도로 보관하는 금액입니다. 실제 상황에 맞게 적립률을 조정해 사용하세요.'],
            ['q' => '부가세는 매출의 10%를 무조건 적립해야 하나요?', 'a' => '매입세액, 면세 매출, 간이과세 여부에 따라 다릅니다. 이 도구의 기본값은 보수적인 현금 관리용 가정이며 실제 신고액은 세무 자료를 기준으로 확인해야 합니다.'],
            ['q' => '다음 달 목표 매출은 무엇을 뜻하나요?', 'a' => '현재 입력한 지출·저축 수준을 유지하고 세금을 적립한다고 가정했을 때, 월말 현금을 줄이지 않기 위해 필요한 매출의 추정치입니다.'],
        ],
    ]),
    'date-calculator' => $tool('date-calculator', '날짜 계산기', 'calculator', '두 날짜 사이의 차이나 특정 날짜 이후의 날짜를 계산합니다.', ['widget' => 'date-calculator', 'related' => ['d-day-calculator', 'age-calculator', 'timestamp']]),
    'd-day-calculator' => $tool('d-day-calculator', 'D-Day 계산기', 'calculator', '목표 날짜까지 남은 일수를 계산합니다.', ['widget' => 'd-day-calculator', 'related' => ['date-calculator', 'age-calculator']]),
    'age-calculator' => $tool('age-calculator', '나이 계산기', 'calculator', '생년월일 기준 만 나이와 연령 정보를 계산합니다.', ['widget' => 'age-calculator', 'related' => ['date-calculator', 'd-day-calculator']]),

    'prompt-formatter' => $tool('prompt-formatter', 'Prompt Formatter', 'ai', 'AI 프롬프트를 구조화하고 읽기 좋게 정리합니다.', ['widget' => 'prompt-formatter', 'is_recent' => true, 'related' => ['prompt-optimizer', 'token-counter']]),
    'prompt-optimizer' => $tool('prompt-optimizer', 'Prompt Optimizer', 'ai', '목표와 조건에 맞게 AI 프롬프트를 개선합니다.', ['widget' => 'prompt-optimizer', 'related' => ['prompt-formatter', 'token-counter']]),
    'token-counter' => $tool('token-counter', 'Token Counter', 'ai', 'AI 입력 텍스트의 토큰 사용량을 추정합니다.', ['widget' => 'token-counter', 'is_popular' => true, 'related' => ['prompt-formatter', 'word-counter']]),

    'url-encode' => $tool('url-encode', 'URL Encode / Decode', 'encoding', 'URL 파라미터와 쿼리 문자열을 인코딩하거나 원래 텍스트로 디코딩합니다.', [
        'widget' => 'url-encode',
        'is_frequent' => true,
        'related' => ['base64', 'jwt-decoder'],
    ]),
    'utm-url-builder' => $tool('utm-url-builder', 'UTM URL 생성기', 'network', '캠페인 추적에 사용할 UTM 파라미터 URL을 생성합니다.', [
        'widget' => 'utm-builder',
        'is_recent' => true,
        'keywords' => ['UTM URL 생성기', '캠페인 URL 빌더', '마케팅 URL 생성'],
        'related' => ['url-encode', 'qr-code'],
    ]),
    'meta-tag-generator' => $tool('meta-tag-generator', '메타태그/OG 태그 생성기', 'network', 'SEO와 소셜 공유에 필요한 meta, Open Graph, Twitter 태그를 생성합니다.', [
        'widget' => 'meta-tag-generator',
        'is_popular' => true,
        'keywords' => ['메타태그 생성기', 'OG 태그 생성기', 'SEO 태그 생성'],
        'related' => ['utm-url-builder', 'url-slug-generator'],
    ]),
    'url-slug-generator' => $tool('url-slug-generator', 'URL 슬러그 생성기', 'network', '제목이나 문장을 URL에 쓰기 좋은 슬러그로 변환합니다.', [
        'widget' => 'url-slug-generator',
        'is_frequent' => true,
        'keywords' => ['URL 슬러그 생성기', 'slug generator', 'SEO URL 변환'],
        'related' => ['url-encode', 'meta-tag-generator'],
    ]),
    'qr-code' => $tool('qr-code', 'QR Code Generator', 'converter', 'URL과 텍스트를 QR 코드 이미지로 만들고 PNG로 내려받습니다.', [
        'widget' => 'qr-code',
        'is_popular' => true,
        'related' => ['url-encode', 'image-to-base64'],
    ]),
    'unit-converter' => $tool('unit-converter', 'Unit Converter', 'converter', '길이, 무게, 면적 단위를 빠르게 변환합니다.', [
        'widget' => 'unit-converter',
        'is_recent' => true,
        'keywords' => ['단위 변환기', '길이 변환', '무게 변환', '평 제곱미터 변환'],
        'related' => ['percent-calculator', 'date-calculator'],
    ]),
    'color-converter' => $tool('color-converter', 'Color Converter', 'color', 'HEX 색상 값을 RGB와 HSL로 변환하고 색상 미리보기를 제공합니다.', [
        'widget' => 'color-converter',
        'is_frequent' => true,
        'related' => ['image-to-base64', 'webp-converter'],
    ]),
];
